# Site settings
title: CIRCIE
email: info@circie.unige.it
description: "CIRCIE - UniGe"
baseurl: ""
url: "http://circie.unige.it"
github_username:  CIRCIE

# Build settings
markdown: kramdown
permalink: pretty
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

theme: minima
